# Generated by Django 3.1 on 2020-08-20 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoOnnorokomSMSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, null=True, verbose_name='Message Text')),
                ('sent_to', models.TextField(verbose_name='Receipents')),
                ('sms_purpose', models.TextField(blank=True, null=True, verbose_name='SMS Purpose')),
                ('mask_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mask Name')),
                ('campaign_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Campaign Name')),
                ('is_success', models.BooleanField(default=False, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_onnorokom_sms_sender', to=settings.AUTH_USER_MODEL, verbose_name='SMS Sent By')),
            ],
            options={
                'verbose_name': 'Django OnnorokomSMS',
                'verbose_name_plural': 'Django OnnorokomSMSs',
                'ordering': ['-created_at'],
            },
        ),
    ]
