# Generated by Django 3.1 on 2020-08-20 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_onnorokom_sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoonnorokomsmsmodel',
            name='response_code',
            field=models.CharField(choices=[('1900', 'Success'), ('1901', 'Parameter content missing'), ('1902', 'Invalid user/pass'), ('1903', 'Not enough balance'), ('1905', 'Invalid destination number'), ('1906', 'Operator Not found'), ('1907', 'Invalid mask Name'), ('1908', 'Sms body too long'), ('1909', 'Duplicate campaign Name'), ('1910', 'Invalid message'), ('1911', 'Too many Sms Request. Please try less than 500 in one request')], default=django.utils.timezone.now, max_length=80, verbose_name='Response Code'),
            preserve_default=False,
        ),
    ]
